apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: mysql-volume
  capacity:
   storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mysql"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: influxdb-volume
  capacity:
   storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/influxdb"

