apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      tier: app
  template:
    metadata:
      labels:
        app: grafana
        tier: app
    spec:
      containers:
        - name: grafana
          image: grafana
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - ./liveness_check.sh
            initialDelaySeconds: 120
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.2
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grafana
  selector:
    app: grafana
    tier: app
  loadBalancerIP: 192.168.49.2
