# # config file version
apiVersion: 1

providers:
 - name: 'influx'
   orgId: 1
   folder: ''
   type: file
   disableDeletion: false
   updateIntervalSeconds: 5
   allowUiUpdates: true
   options:
     path: /usr/share/grafana/public/dashboards
     foldersFromFilesStructure: true
