apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: app
  template:
    metadata:
      labels:
        app: nginx
        tier: app
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 22
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - ./liveness_check.sh
            initialDelaySeconds: 120
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP
    - port: 22
      targetPort: 22
      name: ssh
  selector:
    app: nginx
    tier: app
  loadBalancerIP: 192.168.49.2
