apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: app
  template:
    metadata:
      labels:
        app: wordpress
        tier: app
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - ./liveness_check.sh
            initialDelaySeconds: 120
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.2
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
  selector:
    app: wordpress
    tier: app
  loadBalancerIP: 192.168.49.2
